/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/events/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Form Context */
        get: operations["event_form_context_api_events_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Event */
        post: operations["create_event_api_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Edit Context */
        get: operations["event_edit_context_api_events__event_id__get"];
        /** Update Event */
        put: operations["update_event_api_events__event_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Event Endpoint
         * @description Отмена мероприятия организатором с экрана мероприятия. Права и то, что
         *     мероприятие ещё можно отменить, проверяет тот же `_load_manageable_event`,
         *     что и `PUT /api/events/{id}` (правило 2.7): `404 event_not_found` —
         *     чужой/несуществующий id, `409 event_not_editable` — уже отменено или явка
         *     финализирована, `403 not_an_organizer` — нет прав. Дальше — общий сервис
         *     `cancel_event` (тот же, что у команды `/cancel_event`).
         */
        post: operations["cancel_event_endpoint_api_events__event_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event View */
        get: operations["event_view_api_events__event_id__view_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/rsvp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Event Rsvp */
        post: operations["event_rsvp_api_events__event_id__rsvp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home_api_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{payload}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Events */
        get: operations["project_events_api_projects__payload__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attendance Context */
        get: operations["attendance_context_api_events__event_id__attendance_get"];
        put?: never;
        /** Set Attendance */
        post: operations["set_attendance_api_events__event_id__attendance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{payload}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Settings */
        get: operations["get_project_settings_api_projects__payload__settings_get"];
        /** Update Project Settings */
        put: operations["update_project_settings_api_projects__payload__settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttendanceContext
         * @description Контекст экрана корректировки: подпись проекта/мероприятия и участники.
         */
        AttendanceContext: {
            /** Project Name */
            project_name: string;
            /** Event Label */
            event_label: string;
            /** Finalized */
            finalized: boolean;
            /** Counters Locked */
            counters_locked: boolean;
            /** Participants */
            participants: components["schemas"]["AttendanceParticipant"][];
        };
        /** AttendanceParticipant */
        AttendanceParticipant: {
            /** User Id */
            user_id: number;
            /** Name */
            name: string;
            /** Status */
            status: ("going" | "not_going") | null;
        };
        /**
         * CancelEventResponse
         * @description Итог отмены мероприятия с экрана Web App (задача 2.9.3): удалось ли
         *     перерисовать анонс и скольким подтвердившим участие ушло уведомление.
         */
        CancelEventResponse: {
            /** Announcement Ok */
            announcement_ok: boolean;
            /** Notified */
            notified: number;
        };
        /** CreateEventRequest */
        CreateEventRequest: {
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at?: string | null;
            /** Location */
            location: string;
            /** Description */
            description: string;
            /** Details */
            details?: string | null;
            /** Budget Per Person */
            budget_per_person?: number | string | null;
            /** Seats Limit */
            seats_limit?: number | null;
            /** Co Organizer User Ids */
            co_organizer_user_ids?: number[];
        };
        /** CreateEventResponse */
        CreateEventResponse: {
            /** Event Id */
            event_id: number;
            /** Announcement Message Id */
            announcement_message_id: number | null;
        };
        /**
         * EditEventContext
         * @description Контекст формы редактирования: название проекта, участники для выбора
         *     со-организаторов и текущие значения полей мероприятия.
         */
        EditEventContext: {
            /** Project Name */
            project_name: string;
            /** Members */
            members: components["schemas"]["EventFormMember"][];
            event: components["schemas"]["EventFormData"];
        };
        /** EventCard */
        EventCard: {
            /** Id */
            id: number;
            /** Title */
            title: string | null;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at: string | null;
            /** Location */
            location: string;
            /** Seats Limit */
            seats_limit: number | null;
            /** Going Count */
            going_count: number;
            /** Is Finalized */
            is_finalized: boolean;
        };
        /**
         * EventFormContext
         * @description Контекст для отрисовки формы создания мероприятия.
         */
        EventFormContext: {
            /** Project Name */
            project_name: string;
            /** Members */
            members: components["schemas"]["EventFormMember"][];
        };
        /**
         * EventFormData
         * @description Значения полей мероприятия для предзаполнения формы редактирования.
         */
        EventFormData: {
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at: string | null;
            /** Location */
            location: string;
            /** Description */
            description: string;
            /** Details */
            details: string | null;
            /** Budget Per Person */
            budget_per_person: string | null;
            /** Seats Limit */
            seats_limit: number | null;
            /** Co Organizer User Ids */
            co_organizer_user_ids: number[];
        };
        /** EventFormMember */
        EventFormMember: {
            /** User Id */
            user_id: number;
            /** Name */
            name: string;
            /** Is Self */
            is_self: boolean;
        };
        /** EventRsvpSummary */
        EventRsvpSummary: {
            /** Going Count */
            going_count: number;
            /** Not Going Count */
            not_going_count: number;
            /** My Rsvp */
            my_rsvp: ("going" | "not_going") | null;
        };
        /**
         * EventView
         * @description Мероприятие для экрана Web App (задача 2.9.2): поля + со-организаторы +
         *     сводка RSVP + личная отметка + признак прав на управление + ссылка на анонс.
         *     Доступен любому активному участнику проекта (в отличие от `GET /api/events/
         *     {id}`, требующего прав на управление).
         */
        EventView: {
            /** Id */
            id: number;
            /** Title */
            title: string | null;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at: string | null;
            /** Location */
            location: string;
            /** Description */
            description: string;
            /** Details */
            details: string | null;
            /** Budget Per Person */
            budget_per_person: string | null;
            /** Seats Limit */
            seats_limit: number | null;
            /** Status */
            status: string;
            /** Is Finalized */
            is_finalized: boolean;
            /** Co Organizers */
            co_organizers: components["schemas"]["EventViewCoOrganizer"][];
            rsvp: components["schemas"]["EventRsvpSummary"];
            /** Announcement Url */
            announcement_url: string | null;
            /** Can Manage */
            can_manage: boolean;
        };
        /** EventViewCoOrganizer */
        EventViewCoOrganizer: {
            /** User Id */
            user_id: number;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomeProject */
        HomeProject: {
            /** Payload */
            payload: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /**
         * HomeResponse
         * @description Кто пользователь и в каких он проектах. `projects` пуст → пользователь не
         *     делал `/start` ни в одном чате (состояние «вы не зарегистрированы» на хабе).
         */
        HomeResponse: {
            /** User Name */
            user_name: string;
            /** Projects */
            projects: components["schemas"]["HomeProject"][];
        };
        /** ProjectEventsResponse */
        ProjectEventsResponse: {
            /** Events */
            events: components["schemas"]["EventCard"][];
        };
        /** ProjectSettingsResponse */
        ProjectSettingsResponse: {
            /** Project Name */
            project_name: string;
            /** Reminder Days Threshold */
            reminder_days_threshold: number;
            /** Missed Events Escalation Count */
            missed_events_escalation_count: number;
            /** Reminder Send Hour */
            reminder_send_hour: number;
            /** All Command Throttle Seconds */
            all_command_throttle_seconds: number;
            /** Timezone */
            timezone: string;
            /** Fields */
            fields: components["schemas"]["SettingField"][];
        };
        /**
         * ProjectSettingsUpdate
         * @description Вся форма целиком — фронт всегда шлёт все поля.
         */
        ProjectSettingsUpdate: {
            /** Reminder Days Threshold */
            reminder_days_threshold: number;
            /** Missed Events Escalation Count */
            missed_events_escalation_count: number;
            /** Reminder Send Hour */
            reminder_send_hour: number;
            /** All Command Throttle Seconds */
            all_command_throttle_seconds: number;
            /** Timezone */
            timezone: string;
        };
        /** RsvpRequest */
        RsvpRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "going" | "not_going";
        };
        /** SetAttendanceRequest */
        SetAttendanceRequest: {
            /** User Id */
            user_id: number;
            /** Status */
            status: ("going" | "not_going") | null;
        };
        /** SetAttendanceResponse */
        SetAttendanceResponse: {
            /** User Id */
            user_id: number;
            /** Status */
            status: ("going" | "not_going") | null;
            /** Announcement Refreshed */
            announcement_refreshed: boolean;
            /** Counters Recomputed */
            counters_recomputed: boolean;
        };
        /**
         * SettingField
         * @description Описание одного поля формы — фронт рисует подпись и границы из него, без
         *     хардкода.
         */
        SettingField: {
            /** Attr */
            attr: string;
            /** Describe */
            describe: string;
            /** Kind */
            kind: string;
            /** Min */
            min: number | null;
            /** Max */
            max: number | null;
        };
        /**
         * UpdateEventRequest
         * @description Тело `PUT /api/events/{id}` — те же поля, что и при создании (форма одна,
         *     предзаполненная, TZ §4.3).
         */
        UpdateEventRequest: {
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at?: string | null;
            /** Location */
            location: string;
            /** Description */
            description: string;
            /** Details */
            details?: string | null;
            /** Budget Per Person */
            budget_per_person?: number | string | null;
            /** Seats Limit */
            seats_limit?: number | null;
            /** Co Organizer User Ids */
            co_organizer_user_ids?: number[];
        };
        /** UpdateEventResponse */
        UpdateEventResponse: {
            /** Event Id */
            event_id: number;
            /** Announcement Message Id */
            announcement_message_id: number | null;
            /** Notified Going */
            notified_going: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    event_form_context_api_events_context_get: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventFormContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_events_post: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_edit_context_api_events__event_id__get: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditEventContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_event_api_events__event_id__put: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_event_endpoint_api_events__event_id__cancel_post: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_view_api_events__event_id__view_get: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_rsvp_api_events__event_id__rsvp_post: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RsvpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRsvpSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home_api_home_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_events_api_projects__payload__events_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                payload: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attendance_context_api_events__event_id__attendance_get: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_attendance_api_events__event_id__attendance_post: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAttendanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetAttendanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_settings_api_projects__payload__settings_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                payload: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_settings_api_projects__payload__settings_put: {
        parameters: {
            query?: never;
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                payload: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
