/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/events/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Form Context */
        get: operations["event_form_context_api_events_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Event */
        post: operations["create_event_api_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Edit Context */
        get: operations["event_edit_context_api_events__event_id__get"];
        /** Update Event */
        put: operations["update_event_api_events__event_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attendance Context */
        get: operations["attendance_context_api_events__event_id__attendance_get"];
        put?: never;
        /** Set Attendance */
        post: operations["set_attendance_api_events__event_id__attendance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttendanceContext
         * @description Контекст экрана корректировки: подпись проекта/мероприятия и участники.
         */
        AttendanceContext: {
            /** Project Name */
            project_name: string;
            /** Event Label */
            event_label: string;
            /** Finalized */
            finalized: boolean;
            /** Counters Locked */
            counters_locked: boolean;
            /** Participants */
            participants: components["schemas"]["AttendanceParticipant"][];
        };
        /** AttendanceParticipant */
        AttendanceParticipant: {
            /** User Id */
            user_id: number;
            /** Name */
            name: string;
            /** Status */
            status: ("going" | "not_going") | null;
        };
        /** CreateEventRequest */
        CreateEventRequest: {
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at?: string | null;
            /** Location */
            location: string;
            /** Description */
            description: string;
            /** Budget Per Person */
            budget_per_person?: number | string | null;
            /** Seats Limit */
            seats_limit?: number | null;
            /** Co Organizer User Ids */
            co_organizer_user_ids?: number[];
        };
        /** CreateEventResponse */
        CreateEventResponse: {
            /** Event Id */
            event_id: number;
            /** Announcement Message Id */
            announcement_message_id: number | null;
        };
        /**
         * EditEventContext
         * @description Контекст формы редактирования: название проекта, участники для выбора
         *     со-организаторов и текущие значения полей мероприятия.
         */
        EditEventContext: {
            /** Project Name */
            project_name: string;
            /** Members */
            members: components["schemas"]["EventFormMember"][];
            event: components["schemas"]["EventFormData"];
        };
        /**
         * EventFormContext
         * @description Контекст для отрисовки формы создания мероприятия.
         */
        EventFormContext: {
            /** Project Name */
            project_name: string;
            /** Members */
            members: components["schemas"]["EventFormMember"][];
        };
        /**
         * EventFormData
         * @description Значения полей мероприятия для предзаполнения формы редактирования.
         */
        EventFormData: {
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at: string | null;
            /** Location */
            location: string;
            /** Description */
            description: string;
            /** Budget Per Person */
            budget_per_person: string | null;
            /** Seats Limit */
            seats_limit: number | null;
            /** Co Organizer User Ids */
            co_organizer_user_ids: number[];
        };
        /** EventFormMember */
        EventFormMember: {
            /** User Id */
            user_id: number;
            /** Name */
            name: string;
            /** Is Self */
            is_self: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SetAttendanceRequest */
        SetAttendanceRequest: {
            /** User Id */
            user_id: number;
            /** Status */
            status: ("going" | "not_going") | null;
        };
        /** SetAttendanceResponse */
        SetAttendanceResponse: {
            /** User Id */
            user_id: number;
            /** Status */
            status: ("going" | "not_going") | null;
            /** Announcement Refreshed */
            announcement_refreshed: boolean;
            /** Counters Recomputed */
            counters_recomputed: boolean;
        };
        /**
         * UpdateEventRequest
         * @description Тело `PUT /api/events/{id}` — те же поля, что и при создании (форма одна,
         *     предзаполненная, TZ §4.3).
         */
        UpdateEventRequest: {
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at?: string | null;
            /** Location */
            location: string;
            /** Description */
            description: string;
            /** Budget Per Person */
            budget_per_person?: number | string | null;
            /** Seats Limit */
            seats_limit?: number | null;
            /** Co Organizer User Ids */
            co_organizer_user_ids?: number[];
        };
        /** UpdateEventResponse */
        UpdateEventResponse: {
            /** Event Id */
            event_id: number;
            /** Announcement Message Id */
            announcement_message_id: number | null;
            /** Notified Going */
            notified_going: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    event_form_context_api_events_context_get: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventFormContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_events_post: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_edit_context_api_events__event_id__get: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditEventContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_event_api_events__event_id__put: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attendance_context_api_events__event_id__attendance_get: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_attendance_api_events__event_id__attendance_post: {
        parameters: {
            query?: {
                project?: string | null;
            };
            header?: {
                "X-Telegram-Init-Data"?: string | null;
            };
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAttendanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetAttendanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
