"""initial schema: project, membership, users

Revision ID: 5315a5b9c6d2
Revises: 
Create Date: 2026-08-23 07:10:45.431085

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5315a5b9c6d2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('invite_payload', sa.String(), nullable=False),
    sa.Column('pinned_message_id', sa.BigInteger(), nullable=True),
    sa.Column('default_thread_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project')),
    sa.UniqueConstraint('invite_payload', name=op.f('uq_project_invite_payload')),
    sa.UniqueConstraint('tg_chat_id', name=op.f('uq_project_tg_chat_id'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('tg_user_id', name=op.f('uq_user_tg_user_id'))
    )
    op.create_table('project_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='membershiprole', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'removed', name='membershipstatus', native_enum=False, create_constraint=True), server_default='active', nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by', sa.Integer(), nullable=True),
    sa.Column('last_attended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_missed_events', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_membership_project_id_project')),
    sa.ForeignKeyConstraint(['removed_by'], ['user.id'], name=op.f('fk_project_membership_removed_by_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_project_membership_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_membership')),
    sa.UniqueConstraint('project_id', 'user_id', name=op.f('uq_project_membership_project_id'))
    )
    op.create_table('project_settings',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reminder_days_threshold', sa.Integer(), server_default='14', nullable=False),
    sa.Column('unfilled_checklist_hours', sa.Integer(), server_default='24', nullable=False),
    sa.Column('missed_events_escalation_count', sa.Integer(), server_default='3', nullable=False),
    sa.Column('timezone', sa.String(), server_default='Europe/Moscow', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_settings_project_id_project')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_settings'))
    )
    op.create_table('project_topic_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('events', 'money_collections', 'general', name='topiccategory', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_topic_setting_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_topic_setting')),
    sa.UniqueConstraint('project_id', 'category', name=op.f('uq_project_topic_setting_project_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_topic_setting')
    op.drop_table('project_settings')
    op.drop_table('project_membership')
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
